-- FARM MANAGER V7.2: USERS, ROLES, PERMISSIONS AND ACTIVITY LOG
-- Run this once in Supabase SQL Editor after the earlier V7.1 upgrades.

create table if not exists public.farm_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  farm_id uuid references public.farms(id) on delete cascade,
  full_name text,
  email text,
  role text not null default 'viewer'
    check (role in ('owner','manager','storekeeper','supervisor','viewer')),
  status text not null default 'active'
    check (status in ('active','inactive')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.activity_log (
  id bigint generated by default as identity primary key,
  farm_id uuid references public.farms(id) on delete cascade,
  actor_id uuid references auth.users(id) on delete set null,
  actor_email text,
  table_name text not null,
  record_id text,
  action text not null,
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_farm_user()
returns trigger language plpgsql security definer set search_path=public as $$
declare first_farm uuid; first_role text;
begin
  select id into first_farm from public.farms order by created_at limit 1;
  if not exists (select 1 from public.farm_profiles where role='owner') then
    first_role := 'owner';
  else
    first_role := 'viewer';
  end if;
  insert into public.farm_profiles(id,farm_id,full_name,email,role)
  values(new.id,first_farm,coalesce(new.raw_user_meta_data->>'full_name',''),new.email,first_role)
  on conflict(id) do nothing;
  return new;
end $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute function public.handle_new_farm_user();

-- Backfill users who existed before this upgrade. The earliest becomes owner.
insert into public.farm_profiles(id,farm_id,full_name,email,role)
select u.id, f.id, coalesce(u.raw_user_meta_data->>'full_name',''), u.email,
  case when row_number() over(order by u.created_at)=1 then 'owner' else 'viewer' end
from auth.users u cross join lateral (select id from public.farms order by created_at limit 1) f
on conflict(id) do nothing;

create or replace function public.my_farm_id() returns uuid
language sql stable security definer set search_path=public as
$$ select farm_id from public.farm_profiles where id=auth.uid() and status='active' $$;

create or replace function public.my_farm_role() returns text
language sql stable security definer set search_path=public as
$$ select role from public.farm_profiles where id=auth.uid() and status='active' $$;

alter table public.farm_profiles enable row level security;
alter table public.activity_log enable row level security;
drop policy if exists "profiles_read_same_farm" on public.farm_profiles;
create policy "profiles_read_same_farm" on public.farm_profiles for select
using (farm_id=public.my_farm_id());
drop policy if exists "owner_updates_profiles" on public.farm_profiles;
create policy "owner_updates_profiles" on public.farm_profiles for update
using (farm_id=public.my_farm_id() and public.my_farm_role()='owner')
with check (farm_id=public.my_farm_id());
drop policy if exists "logs_read_owner" on public.activity_log;
create policy "logs_read_owner" on public.activity_log for select
using (farm_id=public.my_farm_id() and public.my_farm_role()='owner');

create or replace function public.write_farm_audit()
returns trigger language plpgsql security definer set search_path=public as $$
declare fid uuid; rid text;
begin
  fid := coalesce((to_jsonb(new)->>'farm_id')::uuid,(to_jsonb(old)->>'farm_id')::uuid,public.my_farm_id());
  rid := coalesce(to_jsonb(new)->>'id',to_jsonb(old)->>'id');
  insert into public.activity_log(farm_id,actor_id,actor_email,table_name,record_id,action)
  values(fid,auth.uid(),auth.jwt()->>'email',tg_table_name,rid,tg_op);
  return coalesce(new,old);
end $$;

do $$
declare t text;
begin
  foreach t in array array['farm_blocks','fields','propagation_batches','crop_cycles',
    'field_activities','workers','irrigation_records','spray_records','inventory_items',
    'harvest_records','equipment']
  loop
    if to_regclass('public.'||t) is not null then
      execute format('drop trigger if exists audit_%I on public.%I',t,t);
      execute format('create trigger audit_%I after insert or update or delete on public.%I for each row execute function public.write_farm_audit()',t,t);
    end if;
  end loop;
end $$;

-- Apply role-aware policies to farm-owned tables. Managers can edit all data;
-- storekeepers manage stock/equipment; supervisors manage field operations.
do $$
declare t text; farm_expr text;
begin
  foreach t in array array['farms','farm_blocks','fields','propagation_batches','crop_cycles',
    'field_activities','workers','irrigation_records','spray_records','inventory_items',
    'harvest_records','equipment']
  loop
    if to_regclass('public.'||t) is null then continue; end if;
    execute format('alter table public.%I enable row level security',t);
    execute format('drop policy if exists v72_read on public.%I',t);
    execute format('drop policy if exists v72_write on public.%I',t);
    farm_expr := case
      when t='farms' then 'id=public.my_farm_id()'
      when t='fields' then 'farm_block_id in (select id from public.farm_blocks where farm_id=public.my_farm_id())'
      when t='crop_cycles' then 'field_id in (select f.id from public.fields f join public.farm_blocks b on b.id=f.farm_block_id where b.farm_id=public.my_farm_id())'
      else 'farm_id=public.my_farm_id()' end;
    execute format('create policy v72_read on public.%I for select using (%s)',t,farm_expr);
    execute format('create policy v72_write on public.%I for all using (%s and (public.my_farm_role() in (''owner'',''manager'') or (public.my_farm_role()=''storekeeper'' and %L in (''inventory_items'',''equipment'')) or (public.my_farm_role()=''supervisor'' and %L in (''propagation_batches'',''crop_cycles'',''field_activities'',''workers'',''irrigation_records'',''spray_records'',''harvest_records'')))) with check (%s and (public.my_farm_role() in (''owner'',''manager'') or (public.my_farm_role()=''storekeeper'' and %L in (''inventory_items'',''equipment'')) or (public.my_farm_role()=''supervisor'' and %L in (''propagation_batches'',''crop_cycles'',''field_activities'',''workers'',''irrigation_records'',''spray_records'',''harvest_records''))))',t,farm_expr,t,t,farm_expr,t,t);
  end loop;
end $$;
